### ISSUE TITLE
Suggestions and issues in code

### ISSUE THREAD

**Issue by ReedCopsey** [FoggyFinder/StudentsWpfTestTask#1]
I'm going to use this to comment on minor suggestions and issues that could be tweaked in the code.

**Comment by ReedCopsey** [comment]
Should this include `first` as well?

https://github.com/FoggyFinder/StudentsWpfTestTask/blob/master/StudentsTask/Components.fs#L58

**Comment by ReedCopsey** [comment]
Looking through this, it seems quite reasonable.

The main changes I would suggestion relate to organization - I'd split up the Student "component" from the app. This makes it a bit more obvious that they are working independently.

**Comment by ReedCopsey** [comment]
I also, personally, like to keep the Navigation in the update method when possible.

In your case, right now, you're doing subscriptions in the component to route to the Navigation system.

Instead, your edit/add could route to a different "app message" (`RequestEdit of Student` or similar), and have the update function route that to the navigation.

That leaves the component "pure" in that it just routes messages out, and the application update loop becomes the one place that changes data + requests dialogs.

I also think, in this case, that would allow you to switch the application to using implicit bindings instead of the Explicit binding API, which would simplify things slightly.

**Comment by FoggyFinder** [comment]
Thank you very much. New API fits perfect. Something left as was, but in the article I noted both options.
